#! /bin/sh
bspc monitor HDMI-0 -d 1 2 3 4
bspc monitor DVI-D-0 -d 5 6 7 8

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          36
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config split_ratio          0.50

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_unplugged_monitor true
spc config remove_disabled_monitor true
bspc config merge_overlapping_monitors false

bspc config normal_border_color		"#3c3836"
bspc config active_border_color		"#3c3836"
bspc config focused_border_color	"#928374"
bspc config presel_feedback_color	"#928374"
bspc config urgent_border_color 	"#fb4934"

bspc config external_rules_command "$HOME/.config/bspwm/external_rules"

bspc rule -a Pavucontrol state=floating
bspc rule -a Shutter state=floating
bspc rule -a Galculator state=floating
bspc rule -a '*:gsimplecal' monitor=DVI-D-0 state=floating follow=off
# bspc rule -a Vivaldi-stable desktop='^1'
bspc rule -a discord desktop='^5'
# bspc rule -a Steam desktop='^2' state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Pcmanfm state=floating follow=on

